### PR TITLE
change file listing method

### PR DESCRIPTION
**Pull request by DeveloppSoft**
Patch the `dapp build` command so dapp can now build files which are not at the root of `./src`.

### CODE REVIEW

**Comment by dbrock** [comment]
I feel like this should probably create a parallel hierarchy in `out/` as well then?

**Comment by DeveloppSoft** [comment]
@dbrock I don't think so, it would complicate too much things, especially regarding testing scripts.
I have a preference for keeping the `out` folder plain.

**Comment by rainbreak** [comment]
@DeveloppSoft how would you deal with same named files? Or would you just disallow this?

e.g.

```
.
└── src
    ├── a
    │   └── thing.sol
    └── b
        └── thing.sol
```

With a tree in `out` this would give `out/a/thing.json` and `out/b/thing.json`, but what do you suggest if `out` is flat instead?

**Comment by DeveloppSoft** [comment]
Yeah, didn't thought about that, what about forbidding it for the moment?

**Comment by dbrock** [comment]
I think it has to be a parallel hierarchy, it doesn't make sense to me otherwise

**Comment by DeveloppSoft** [comment]
Ok let's close that, I don't have time to improve it

**Comment by rainbreak** [comment]
replaced by #52

**Pull request closed without merging**
